# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  quality:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        os: [ubuntu-latest, macOS-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: test
